export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    {name: 'general', title: 'General'},
    {name: 'contact', title: 'Contact'},
    {name: 'social', title: 'Social'},
  ],
  fields: [
    {
      name: 'companyName',
      title: 'Company Name',
      type: 'string',
      initialValue: 'Olatmatics Tech Hub Ltd',
      group: 'general',
    },
    {
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      initialValue: 'Engineering & Automation · Abuja',
      group: 'general',
    },
    {
      name: 'description',
      title: 'Meta Description',
      type: 'text',
      group: 'general',
    },
    {
      name: 'logo',
      title: 'Logo',
      type: 'image',
      group: 'general',
    },
    {
      name: 'address',
      title: 'Office Address',
      type: 'string',
      initialValue: 'Federal Housing Lugbe, Abuja, Nigeria',
      group: 'contact',
    },
    {
      name: 'phone1',
      title: 'Primary Phone',
      type: 'string',
      initialValue: '08039790207',
      group: 'contact',
    },
    {
      name: 'phone2',
      title: 'Secondary Phone',
      type: 'string',
      initialValue: '08074591971',
      group: 'contact',
    },
    {
      name: 'email',
      title: 'Email Address',
      type: 'string',
      initialValue: 'olatmatics.tech@gmail.com',
      group: 'contact',
    },
    {
      name: 'whatsappUrl',
      title: 'WhatsApp URL',
      type: 'url',
      initialValue: 'https://wa.link/uxd689',
      group: 'social',
    },
    {
      name: 'minBudget',
      title: 'Minimum Engagement Budget',
      type: 'string',
      initialValue: '₦200,000',
      group: 'general',
    },
    {
      name: 'footerCopyright',
      title: 'Footer Copyright Text',
      type: 'string',
      initialValue: '© 2025 Olatmatics Tech Hub Limited. All rights reserved.',
      group: 'general',
    },
  ],
}
